version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5433:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
